### ISSUE TITLE
EC block balance increase index is incorrect

### ISSUE THREAD

**Issue by carryforward** [FactomProject/WorkItems#590]
paul and beam probably need to work together on this one.

**Comment by carryforward** [comment]
I must have been really tired when I made this one (yep, 3:30AM)  

The index is the offset into the factoid transaction, not the offset into the factoid block

**Comment by carryforward** [comment]
but the test script ~/go/src/github.com/FactomProject/factom-cli/trans.sh makes a single factoid transaction with two EC purchases.  I only saw the indexes as being zero.  The first one should be zer0 and the second one in the factoid transaction should be 1

**Comment by PaulSnow** [comment]
This should be fixed.  Is it?

**Comment by carryforward** [comment]
nope, not fixed

to replicate:

run ~/go/src/github.com/FactomProject/factom-cli/trans.sh

look in EC block.  I see:

```
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0C 
40 73 9D 3C 8E 05 C6 87 0C 8D 90 1A 9A 40 E1 B2 E1 C8 AD F5 A1 2E 9B 93 76 27 F6 E4 6E 5A 87 95 
B5 23 09 33 E0 B3 E5 09 BB C6 24 36 E1 7A 98 5A DC 63 21 51 36 B1 AC 07 CC 5E 35 67 A2 03 0C BB 
51 E9 86 64 08 D3 2A 11 C1 E2 71 DA 0F 9A 38 52 83 80 D4 EE 2C 1D 4F F5 F3 8A B5 AE AA 88 52 12 
00 00 00 09 
00 
00 00 00 00 00 00 00 0D 
00 00 00 00 00 00 00 9E 
00 00 

04 E5 56 C6 CD 04 A2 F2 B5 E9 CA 74 9F 8B 73 98 51 61 1E 51 26 48 CA C9 C6 FB 3F 70 95 64 82 1D 1D 5D 4F E7 72 FA A5 FD 40 44 EC DF BF 8A B2 CB 63 AA 74 03 1F 65 DB 94 40 A3 24 10 47 78 A3 2C 19 00 8A 76 
04 21 B5 56 5E 9C 74 9E 54 C6 71 C2 E8 9B 8E BA CF 7E 1F 77 BC 91 86 F1 0E 07 BD C9 6A 9B 7D CF 74 5D 4F E7 72 FA A5 FD 40 44 EC DF BF 8A B2 CB 63 AA 74 03 1F 65 DB 94 40 A3 24 10 47 78 A3 2C 19 00 8A 76 

01 01 01 02 01 03 01 04 01 05 01 06 01 07 01 08 01 09 01 0A
```


The two balance increases are:

```
04 
E5 56 C6 CD 04 A2 F2 B5 E9 CA 74 9F 8B 73 98 51 61 1E 51 26 48 CA C9 C6 FB 3F 70 95 64 82 1D 1D <pubkey
5D 4F E7 72 FA A5 FD 40 44 EC DF BF 8A B2 CB 63 AA 74 03 1F 65 DB 94 40 A3 24 10 47 78 A3 2C 19 <txid
00 <index into transaction
8A 76 <Num ECs



04 
21 B5 56 5E 9C 74 9E 54 C6 71 C2 E8 9B 8E BA CF 7E 1F 77 BC 91 86 F1 0E 07 BD C9 6A 9B 7D CF 74 <pubkey
5D 4F E7 72 FA A5 FD 40 44 EC DF BF 8A B2 CB 63 AA 74 03 1F 65 DB 94 40 A3 24 10 47 78 A3 2C 19 <txid
00 <index into transaction (should be 1)
8A 76 <Num ECs
```

since there were two purchases in the factoid transaction, the second one should have an offset

**Comment by carryforward** [comment]
This is the factoid transaction:

```
02 
01 4F 24 90 F3 51 <timestamp
01 <input count
01 <output count
02 <EC purchase count
88 83 A1 A8 68 <amount factoids in
CB B1 E0 A0 44 4B 42 1F D8 C2 06 22 50 18 7E 2E 50 9B 62 76 A9 F3 5B 61 68 1D D5 21 92 71 85 3F <factoid input
C7 C3 A3 00 <amount factoids out
01 C1 75 74 20 8C 78 BC 39 AD F1 73 55 98 98 D7 82 69 C4 0B 1A BD D7 D6 2D F8 48 A3 35 BC F2 D5 <factoid output
83 BC BA EF 20 <amount EC0
E5 56 C6 CD 04 A2 F2 B5 E9 CA 74 9F 8B 73 98 51 61 1E 51 26 48 CA C9 C6 FB 3F 70 95 64 82 1D 1D <EC key index 0
83 BC BA EF 20 <amount EC1
21 B5 56 5E 9C 74 9E 54 C6 71 C2 E8 9B 8E BA CF 7E 1F 77 BC 91 86 F1 0E 07 BD C9 6A 9B 7D CF 74 <EC key index 1

\/ sigs, etc
01 F0 16 80 76 C4 AA 36 F5 09 CF 26 33 A8 7C 20 9E FF 80 5F 3C EA 69 05 AD 4B FA 1E E0 8C 27 F4 BC 85 AF F3 1D CB B6 F3 FF 48 2D 4E 68 02 0F 2A 62 5A F7 F8 B9 E6 D6 8F 47 7D 52 64 DD CA 44 81 43 AB 68 2E 43 A4 02 47 48 33 56 3E 2C DE 61 7D AF A7 29 AD 17 7F 08 26 53 60 63 DD D7 81 41 19 06 
```

**Comment by michaelbeam** [comment]
The issue is fixed. please test with 10 min blocks
