### ISSUE TITLE
fctwallet should handle hex encoded public keys in transactions

### ISSUE THREAD

**Issue by michaelbeam** [FactomProject/WorkItems#649]
e.g.

	% factom-cli balance ec 4903d15294e567ab31f0cec11520b87d4f55852e35660fa599ef9d79fc352486
	Key is too long.  Keys must be less than 32 characters

/home/mjb/work/factom/go/src/github.com/FactomProject/fctwallet/handlers/transaction.go:38

Wallet handler should recognize hex encoded pubkey.

**Comment by carryforward** [comment]
This also breaks with human readable keys too:

```
factom-cli addecoutput newtrans EC2DKSYyRcNWf7RS963VFYgMExoHRYLHVeCfQ9PGPmNzwrcmgm2r 49
Key is too long.  Keys must be less than 32 characters
```

**Comment by PaulSnow** [comment]
Fixed.

**Comment by carryforward** [comment]
yep checks out.  Creating transactions with hex keys is still broken, but I think that's ok.
